
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomDatabase } from './custom-types';

const SUPABASE_URL = "https://poyvathmzabebdytcmip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBveXZhdGhtemFiZWJkeXRjbWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjYzMzUsImV4cCI6MjA2MDAwMjMzNX0.fQmZ-w9XzSwea048Sbf29p1oCg_5mCYxoZk1dWKbikI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<CustomDatabase>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
